import { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const AboutUs: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>About Us</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <h1 className={styles.title}>
        About Us
      </h1>
    </main>
  </div>
);

export default AboutUs;
